composer.json
examples/union_types.php
src/Configuration/Defaults/CommonAdditionalRules.php
src/Configuration/Defaults/CommonSkippedRules.php
src/Fixers/BinaryOperatorSpacesFixer.php
src/Fixers/FixerWorkaround.php
src/Fixers/NoSpacesAfterFunctionNameFixer.php
tests/AdditionalRulesConfigurationTest.php
tests/SkippedRulesConfigurationTest.php

Now this is correct:
```php
<?php
class Whatever
{
public int|string $something;
/**
* @throws JsonException
*/
public function do(): void
{
$i = 1 + 1;
json_encode([$i], JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);
}
}
```

#15 - BinaryOperatorSpacesFixer fixed

---

.github/workflows/check.yml
composer.json
readme.md
src/Configuration/Defaults/CommonAdditionalRules.php
tests/AdditionalRulesConfigurationTest.php
tests/LaravelPathsConfigurationTest.php

After this change, all useless comments will be removed:
Before:
```php
<?php
/**
* Class Whatever
*/
class Whatever
{
public int|string $something;
/**
* @throws JsonException
*/
public function do(): void
{
$i = 1 + 1;
json_encode([$i], JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);
}
}
```
After:
```php
<?php
class Whatever
{
public int|string $something;
/**
* @throws JsonException
*/
public function do(): void
{
$i = 1 + 1;
json_encode([$i], JSON_THROW_ON_ERROR | JSON_UNESCAPED_SLASHES);
}
}
```
This should close #19.

#19 - removing useless phpdoc comments

---

ecs.php
readme.md
src/Config.php
src/Configuration/Defaults/CommonAdditionalRules.php
src/Fixers/DoubleQuoteFixer.php
tests/codestyle/config.php
tests/codestyle/fixtures/trailingCommas/actual.php
tests/codestyle/fixtures/trailingCommas/expected.php
tests/unit/AdditionalRulesConfigurationTest.php
tests/unit/LaravelPathsConfigurationTest.php
tests/unit/SkippedRulesConfigurationTest.php

it should close #30
<details>
<summary>Before</summary>
```php
<?php
class TrailingCommasExample
{
public function testArguments(): string
{
return $this->testParameters(
"a",
"b"
);
}
public function testParameters(
string $a,
string $b
): string {
return "${a}-${b}";
}
public function testArrays(): array
{
return [
1,
2,
3
];
}
}
```
</details>
<details>
<summary>After</summary>
```php
<?php
class TrailingCommasExample
{
public function testArguments(): string
{
return $this->testParameters(
"a",
"b",
);
}
public function testParameters(
string $a,
string $b,
): string {
return "${a}-${b}";
}
public function testArrays(): array
{
return [
1,
2,
3,
];
}
}
```
</details>

#30 - enforce trailing commas

---

src/Configuration/Defaults/CommonAdditionalRules.php
tests/codestyle/fixtures/operatorSpacing/actual.php
tests/codestyle/fixtures/operatorSpacing/expected.php
tests/unit/AdditionalRulesConfigurationTest.php

It should close #26 
<details>
<summary>Before</summary>
```php
<?php
$a=1+2;
$b=$a===3;
$c=$a<5;
$d=!$c;
```
</details>
<details>
<summary>After</summary>
```php
<?php
$a = 1 + 2;
$b = $a === 3;
$c = $a < 5;
$d = !$c;
```
</details>

#26 - spaces around operators

---

src/Configuration/Defaults/CommonAdditionalRules.php
tests/codestyle/fixtures/nullableTypeForDefaultNull/actual.php
tests/codestyle/fixtures/nullableTypeForDefaultNull/expected.php
tests/unit/AdditionalRulesConfigurationTest.php

Before:
```php
<?php
class NullableTypeForDefaultNull
{
public function getNameLabel(string $name, string $title = null): string
{
$label = $name;
if ($title !== null) {
$label .= " " . $title;
}
return $label;
}
}
```
After:
```php
<?php
class NullableTypeForDefaultNull
{
public function getNameLabel(string $name, ?string $title = null): string
{
$label = $name;
if ($title !== null) {
$label .= " " . $title;
}
return $label;
}
}
```

#40 - forcing nullable type declaration for default null values

---

.github/workflows/check.yml
composer.json
docker-compose.yml
tests/codestyle/CodestyleTest.php
tests/codestyle/fixtures/enums/actual.php
tests/codestyle/fixtures/enums/expected.php

Okay, so I updated ECS and PHP-CS_Fixer underneath. Enums are working properly right now.
The problem to discuss is versioning. I bumped development environment Docker to 8.1 and everything is okay. But if anyone would like to run tests with PHP 8.0, then it'd break because it'd not understand enum syntax. Generally Codestyle as a package should work with PHP 8.0 projects (the problem is for internal testing only).
Should we exclude this one particular test from test cases for PHP < 8.1? Or maybe we should just bump required PHP version to 8.1? I'm open to discussion.
It should close #42.

#42 - enums fixed with SwitchCaseSemicolonToColonFixer update

---

composer.json
tests/codestyle/CodestyleTest.php
tests/codestyle/fixtures/readonlies/actual.php
tests/codestyle/fixtures/readonlies/expected.php
tests/codestyle/fixtures/references/actual.php
tests/codestyle/fixtures/references/expected.php

I bumped ECS underneath, so readonlies and references in methods should be working now.
Should close #45.

#45 - references in method signatures

---

composer.json
ecs.php
licence.md
src/Configuration/Defaults/CommonAdditionalRules.php
tests/unit/AdditionalRulesConfigurationTest.php

It should close #49 and fix #48.
I removed deprecated `InternalClassCasingFixer`. It looks like after that everything is working fine.

#49 - deprecated InternalClassCasingFixer removed

---

src/Config.php
src/Configuration/Defaults/CommonRules.php
src/Configuration/Defaults/LaravelPaths.php
tests/codestyle/CodestyleTest.php
tests/codestyle/fixtures/classAttributesSeparation/actual.php
tests/codestyle/fixtures/classAttributesSeparation/expected.php
tests/codestyle/fixtures/noUselessParenthesisFixer/actual.php
tests/codestyle/fixtures/noUselessParenthesisFixer/expected.php

This should close #55.
Added `NoUselessParenthesisFixer` and `ClassAttributesSeparationFixer` from Kuba Werłos custom fixers.
**ClassAttributesSeparationFixer**
Before:
```php
<?php
class classAttributesSeparationExample
{
use $exampleTraitA;
use $exampleTraitB;
protected string $exampleA;
protected string $exampleB;
public function testFunctionA(string $a): string
{
return $a;
}
public function testFunctionB(string $b): string
{
return $b;
}
}
```
After:
```php
<?php
class classAttributesSeparationExample
{
use $exampleTraitA;
use $exampleTraitB;
protected string $exampleA;
protected string $exampleB;
public function testFunctionA(string $a): string
{
return $a;
}
public function testFunctionB(string $b): string
{
return $b;
}
}
```
**NoUselessParenthesisFixer** …

#55 - class attributes separation and useless parenthesis

---

composer.json
src/Config.php
src/Configuration/Defaults/CommonRules.php
src/Fixers/NoLaravelMigrationsGeneratedCommentFixer.php
tests/codestyle/CodestyleTest.php
tests/codestyle/fixtures/laravelMigrations/actual.php
tests/codestyle/fixtures/laravelMigrations/expected.php
tests/codestyle/fixtures/phpdocs/actual.php
tests/codestyle/fixtures/phpdocs/expected.php

This should close #58 and #38.
With this proposed changes following code:
```php
<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration
{
/**
* Run the migrations.
*
* @return void
*/
public function up()
{
Schema::create("sessions", function (Blueprint $table) {
$table->string("id")->primary();
$table->text("payload");
});
}
/**
* Reverse the migrations.
*
* @return void
*/
public function down()
{
Schema::dropIfExists("sessions");
}
};
```
would be restyled into:
```php
<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class() extends Migration {
public …
```

#58 - remove Laravel migrations stub comments

---

readme.md
src/Configuration/Defaults/CommonRules.php

`ExplicitStringVariableFixer` was forcing us to add curly braces for string interpolation. As it's mostly useless and annoying and it probably will be deprecated with PHP 8.2, I'm removing it from common rules.
This should close #68.

#68 - do not enforce ${} string interpolation

---

src/Configuration/Defaults/CommonRules.php
tests/codestyle/CodestyleTest.php
tests/codestyle/fixtures/yodaStyle/actual.php
tests/codestyle/fixtures/yodaStyle/expected.php

This should close #69 .
**Before:**
```
<?php
if (null === $a) {
echo "null";
}
```
**After:**
```
<?php
if ($a === null) {
echo "null";
}
```

#69 - added non-yoda style fixer

---

composer.json
src/Configuration/Defaults/CommonRules.php
tests/codestyle/CodestyleTest.php
tests/codestyle/fixtures/anonymousFunctions/actual.php
tests/codestyle/fixtures/anonymousFunctions/expected.php
tests/codestyle/fixtures/objectOperators/actual.php
tests/codestyle/fixtures/objectOperators/expected.php

With these changes this:
```php
$array = $this ->array;
if ($this ?-> nullable) {
return array_filter($array, fn (int $i): bool => $i % 2 === 0);
}
```
will be fixed into:
```php
$array = $this->array;
if ($this?->nullable) {
return array_filter($array, fn(int $i): bool => $i % 2 === 0);
}
```
---
This should close #74 and should close #11 again.

#74 - object operator spacing

---

composer.json
src/Configuration/Defaults/CommonRules.php
tests/codestyle/fixtures/trailingCommas/actual.php
tests/codestyle/fixtures/trailingCommas/expected.php

With this pull request this:
```php
return match ($i) {
1 => 1,
2 => 3,
default => 0
};
```
will be transformed to this:
```php
return match ($i) {
1 => 1,
2 => 3,
default => 0,
};
```
This should finally close #39.

#39 - trailing commas for match expressions

---

src/Configuration/Defaults/CommonRules.php
src/Tools/CodestyleFileInitializer.php
src/Tools/ComposerManifestScriptsInitializer.php
tests/codestyle/CodestyleTest.php
tests/codestyle/fixtures/stringVariables/actual.php
tests/codestyle/fixtures/stringVariables/expected.php
tests/codestyle/fixtures/trailingCommas/actual.php
tests/codestyle/fixtures/trailingCommas/expected.php

As `"Hello ${test}!"` syntax will be deprecated in PHP8.2, I added a rule to remove it from our codebase.
It will be a little pain in the ass, because before the release 1.3.0 the old syntax was a default style for inline string interpolation. Be ready for multiple files changed in all projects.
This closes #80 and it's connected to #68.

#80 - simple to complex string variables

---

src/Configuration/Defaults/CommonRules.php

With https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6658 PHP CS Fixer broke default spacing for `fn()`s. This PR returns it.
It's again connected to #11.

#11 - anonymous functions spacing

---

.github/workflows/check.yml
composer.json

With my changes from https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6674 the number of checked/to-be-fixed files should be displayed in your console:
```
dcr php composer cs
Creating codestyle_php_run ... done
> ./vendor/bin/php-cs-fixer fix --dry-run --diff --config codestyle.php
Loaded config Blumilk codestyle standard from "codestyle.php".
Found 0 of 18 files that can be fixed in 0.542 seconds, 16.000 MB memory used
```
This should close #73.

#73 - printing number of checked files

---

.github/workflows/check.yml
composer.json
docker-compose.yml
src/Configuration/Defaults/LaravelPaths.php
tests/codestyle/CodestyleTest.php
tests/codestyle/fixtures/php82/actual.php
tests/codestyle/fixtures/php82/expected.php

As PH 8.0 lost its active support with November 2022, we finally dropping support for that version in our Codestyle. Additionally authors of PHP-CS-Fixer finally released 3.15 with PHP 8.2 support, so our package should handle newest PHP in our projects.
This should close #85.

#85 - drop PHP 8.0 support

---

composer.json
readme.md
src/Configuration/Defaults/CommonRules.php
tests/codestyle/CodestyleTest.php
tests/codestyle/fixtures/emptyLines/actual.php
tests/codestyle/fixtures/emptyLines/expected.php
tests/codestyle/fixtures/objectOperators/expected.php
upgrading.md

I added new fixers to common ruleset:
* [no_empty_comment](https://mlocati.github.io/php-cs-fixer-configurator/#version:3.15|fixer:no_empty_comment)
* [no_trailing_comma_in_singleline](https://mlocati.github.io/php-cs-fixer-configurator/#version:3.15|fixer:no_trailing_comma_in_singleline)
* [magic_method_casing](https://mlocati.github.io/php-cs-fixer-configurator/#version:3.15|fixer:magic_method_casing)
* [native_function_casing](https://mlocati.github.io/php-cs-fixer-configurator/#version:3.15|fixer:native_function_casing)
* [lambda_not_used_import](https://mlocati.github.io/php-cs-fixer-configurator/#version:3.15|fixer:lambda_not_used_import)
* [no_homoglyph_names](https://mlocati.github.io/php-cs-fixer-configurator/#version:3.15|fixer:no_homoglyph_names)
* …

- common ruleset update

---

composer.json
src/Configuration/Defaults/CommonRules.php
tests/codestyle/CodestyleTest.php
tests/codestyle/fixtures/importsOrder/actual.php
tests/codestyle/fixtures/importsOrder/expected.php

In another project I found out that codestyle is not checking imports ordering and grouping properly.
With this pull request these imports:
```php
use function array_merge;
use function assert;
use Something\Api;
use Something\Paths;
use const Something\CONSTANT;
use Whatever\File;
use Whatever\SpecificationFile;
use Whatever\Reader;
```
will look like [PSR-12 guideline](https://www.php-fig.org/psr/psr-12/#3-declare-statements-namespace-and-import-statements):
```php
use Something\Api;
use Something\Paths;
use Whatever\File;
use Whatever\Reader;
use Whatever\SpecificationFile;
use function array_merge;
use function assert;
use const Something\CONSTANT;
```
So this pull request:
* should close #91 
* updates dependencies
* changes the way the imports are sorted and grouped
* removes …

#91 - ordering and grouping imports

---

src/Config.php
src/Configuration/Defaults/CommonRules.php
src/Configuration/Defaults/Rules.php
src/Fixers/DoubleQuoteFixer.php
src/Fixers/NoCommentFixer.php
src/Fixers/NoLaravelMigrationsGeneratedCommentFixer.php
tests/codestyle/CommonRulesetTest.php
tests/codestyle/fixtures/blankLineBeforeStatement/actual.php
tests/codestyle/fixtures/blankLineBeforeStatement/expected.php
tests/codestyle/fixtures/nullableTypeForDefaultNull/expected.php
tests/codestyle/fixtures/objectOperators/expected.php

This should close #94.
With these changes this:
```
public function getFoo(int $foo): int {
$bar = $foo;
return $bar;
}
```
will be fixed into:
```
public function getFoo(int $foo): int {
$bar = $foo;
return $bar;
}
```

#94 - return statement missing blank line fixer

---

composer.json
src/Configuration/Defaults/CommonRules.php
tests/fixtures/noMultilineWhitespaceAroundDoubleArrow/actual.php
tests/fixtures/noMultilineWhitespaceAroundDoubleArrow/expected.php

This should close #105.
Actual:
```
public function getArray1(): array
{
return [
];
}
public function getArray2(): array
{
return [1
=> 2];
}
public function getClosure(): Closure
{
return fn() =>
[];
}
```
Expected:
```
public function getArray1(): array
{
return [];
}
public function getArray2(): array
{
return [1 => 2];
}
public function getClosure(): Closure
{
return fn() => [];
}
```
Fixed in `composer.json` scripts for running tests. From `--colors always` to `--colors=always`.

#105 - array no multiline whitespace

---

composer.json
src/Config.php
src/Configuration/Defaults/CommonRules.php
tests/codestyle/CommonRulesetTest.php
tests/fixtures/classesImport/actual.php
tests/fixtures/classesImport/expected.php

With this PR this code:
```php
<?php
class TestException extends \Exception
{
protected string $rules = "\Blumilk\Codestyle\Configuration\Defaults\LaravelPaths";
public function rules(\Blumilk\Codestyle\Configuration\Defaults\CommonRules $rules): void
{
echo 123;
}
}
```
should be transformed into:
```php
<?php
use Blumilk\Codestyle\Configuration\Defaults\CommonRules;
use Blumilk\Codestyle\Configuration\Defaults\LaravelPaths;
class TestException extends Exception
{
protected string $rules = LaravelPaths::class;
public function rules(CommonRules $rules): void
{
echo 123;
}
}
```
So:
* all imports should be imported in import section
* all hardcoded class names should be transformed to FQCNs and imported as well
Additionally:
* deprecated `CurlyBracesPositionFixer` …

- importing FQCNs

---

src/Config.php
src/Configuration/Defaults/CommonRules.php
src/Fixers/NamedArgumentFixer.php
tests/codestyle/CodestyleTestCase.php
tests/codestyle/CommonRulesetTest.php
tests/fixtures/namedParameters/actual.php
tests/fixtures/namedParameters/expected.php

Should close #43.
Added named parameters fixer and tests for that fixer.
**Before:**
```
<?php
$class = new ErrorsThresholdExceeded(
requestsNumber :$requests,
errorsNumber   :  $errors,
percentage     :          $percentage,
);
$result = $reader->merge($merge, new Api(), flag     :   CONSTANT);
```
**After:**
```
<?php
$class = new ErrorsThresholdExceeded(
requestsNumber: $requests,
errorsNumber: $errors,
percentage: $percentage,
);
$result = $reader->merge($merge, new Api(), flag: CONSTANT);
```

#43 - named parameters fixer

---

src/Configuration/Defaults/CommonRules.php
tests/fixtures/emptyLines/actual.php
tests/fixtures/emptyLines/expected.php

With this PR codestyle package should not accept empty lines between docblocks and other elements.
In general this:
```php
/**
* @property Uuid $user_id
* @property Uuid $id
* (...)
*/
class Alert extends Model
{
```
should be replaces with this:
```php
/**
* @property Uuid $user_id
* @property Uuid $id
* (...)
*/
class Alert extends Model
{
```
Ref:
* https://github.com/blumilksoftware/city-alert-core/blob/90f0973eb894037061ae067fe2d681bf06c2c0ce/app/Models/Alert.php#L37

#87 - no empty lines after docblocks

---

bin/codestyle

Should close #108.
Added two levels for `autoload.php` path.
Tested on Laravel project with Blumilk `codestyle`.

#108 - init command bug fix

---

composer.json
src/Fixers/NoCommentFixer.php

This PR fixes NoCommentFixer after 3.59.3 php cs fixer release.
Close #124

#124 - fix NoCommentFixer.php after 3.59.3 php cs fixer release

---

src/Config.php
src/Configuration/Defaults/CommonRules.php
src/Fixers/ClassKeywordFixer.php
tests/codestyle/CommonRulesetTest.php
tests/fixtures/classesImport/actual.php
tests/fixtures/classesImport/expected.php

Should close #112.
**Before:**
```
class TestException extends \Exception
{
protected string $var = "Error";
protected string $class = "\Error";
protected string $laravel = "LaravelPaths";
protected string $bar = "\PhpCsFixer\Tokenizer\Tokens";
protected string $foo = "PhpCsFixer\Tokenizer\Tokens";
protected string $faz = "\Tokens";
public function rules(\Blumilk\Codestyle\Configuration\Defaults\CommonRules $rules): void
{
echo 123;
}
public function test(): void
{
$foo = 'Blumilk\Codestyle\Configuration\Defaults\Paths';
$baz = "\Exception";
$fuz = "Exception";
}
}
```
**After:**
```
use Blumilk\Codestyle\Configuration\Defaults\CommonRules;
class TestException extends Exception
{
protected string $var = "Error";
protected string $class = \Error::class;
protected …
```

#112 - class keyword fixer

---

src/Configuration/Defaults/CommonRules.php
tests/codestyle/CommonRulesetTest.php
tests/fixtures/spacesInsideParentheses/actual.php
tests/fixtures/spacesInsideParentheses/expected.php

Should close #127.
Before:
```
<?php
$foo = explode("\\", $class );
$baz = [ "foo", "bar" , "baz" ];
```
After:
```
<?php
$foo = explode("\\", $class);
$baz = ["foo", "bar", "baz"];
```

#127 - spaces inside parentheses fixer

---

.gitattributes

With this PR, files like Makefile, Docker stuff and Github Actions won't be added to the vendor directories of projects using this package.

- ignoring some files from Composer

---

.gitattributes
composer.json
docker-compose.yml
src/Configuration/Defaults/CommonRules.php
tests/fixtures/phpdocs/actual.php
tests/fixtures/phpdocs/expected.php

This PR changes thing like this (completely random, but used by Laravel team):
```php
class VerifyCsrfToken extends BaseVerifyCsrfToken
{
/**
* @param Request $request
* @param  array  $config
*/
protected function newCookie($request, $config): Cookie
{
```
to this:
```php
class VerifyCsrfToken extends BaseVerifyCsrfToken
{
/**
* @param Request $request
* @param array $config
*/
protected function newCookie($request, $config): Cookie
{
```
Also:
* updated PHP version in docker development mode
* ignore renovate file for Packagist
* updated dependencies
This should close #134.

#134 - phpdocs items spacing
